# Generated by Django 4.2.4 on 2023-11-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    forward = """
        INSERT INTO plugins (
            pluginid, name, icon, component, componentname, config, slug, sortorder)
        VALUES (
            'af06e949-5e16-49f0-b23e-e8529e8ce321',
            'Dashboard',
            'fa fa-pie-chart',
            'views/components/plugins/dashboard',
            'dashboard', 
            '{"show": true, "is_workflow": false, "description": ""}',
            'dashboard',
            '1'
        );
        """
    
    reverse = """
        DELETE FROM plugins where pluginid = 'af06e949-5e16-49f0-b23e-e8529e8ce321';
        DELETE FROM system_record;
        """

    operations = [
        migrations.CreateModel(
            name='SystemRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_details', models.JSONField(blank=True, null=True)),
                ('state_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_record',
                'managed': True,
            },
        ),
        migrations.RunSQL(forward, reverse),
    ]
